name: Build_cs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: |
          选择 OpenWrt 分支
        required: true
        default: "immortalwrt"
        type: choice
        options:
          - immortalwrt
          - openwrt
          
env:
  SSH: false
  UPLOAD_BIN_DIR: false
  PATH_CACHE: /tmp/.cache
  CACHE_IMAGE: imagebuilder:${{ inputs.image }}-${{ inputs.version }}.tar

jobs:
  Build:
    name: Build ${{ inputs.branch }}-${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure docker image
        run: |
          chmod +x ${{ github.workspace }}/.github/.sh/echo.sh
          ..${{ github.workspace }}/.github/.sh/echo.sh